[colors.cursor]
cursor = "0xcdd6f4"
text = "0x1e1e2e"

[colors.normal]
black = "0x494d64"
blue = "0x8aadf4"
cyan = "0x8bd5ca"
green = "0xa6da95"
magenta = "0xf5bde6"
red = "0xed8796"
white = "0xb8c0e0"
yellow = "0xeed49f"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[font]
size = 12

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[window]
blur = true
decorations = "none"
dynamic_padding = true
opacity = 0.4

[window.padding]
x = 8
y = 8
